### PR TITLE
Add BuildTime config for websocket path

### PR DESCRIPTION
**Pull request by indiealexh**
Related to #30

Enables the use of a customized path for the JsonRPC over WebSockets with:

`quarkus.json-rpc.web-sockets.path`

Enables the ability to disable JsonRPC over Websockets with:

`quarkus.json-rpc.web-sockets.enabled`

I added this as JsonRPC does not specify a specific transport, so expanding to transport over other protocols should be considered for the future.

### CODE REVIEW

**Comment by indiealexh** [comment]
May close in favor of path on the annotation in alignment with extensions like websocket-next

**Review by phillip-kruger — APPROVED** [review]
Great ! Thanks ! I think the adoc will be generated from the JavaDoc in the Config, so you can remove that (we need documentation still, but as soon as that is created the config table should be generated automatically)

**Comment by indiealexh** [comment]
> Great ! Thanks ! I think the adoc will be generated from the JavaDoc in the Config, so you can remove that (we need documentation still, but as soon as that is created the config table should be generated automatically)

I'll do the clean up and mark pr ready.

**Comment by indiealexh** [comment]
@phillip-kruger Ready for review

**Review by phillip-kruger — APPROVED** [review]
Thanks very much for your contribution !

**Pull request merged**
