### PR TITLE
Improve CDI handling of JsonRPCRouter

### PR DESCRIPTION
**Pull request by geoand**
Use a SyntheticBeanBuildItem in order to ensure
bean is created via it's constructor without
hidden references to Arc or CDI in the creation
process

### CODE REVIEW

**Review by phillip-kruger — APPROVED** [review]
Nice ! I thinks this can be done in GraphQL too

**Comment by geoand** [comment]
🙏

**Comment by phillip-kruger** [comment]
This can probably also be done in Vertx-http (dev ui) as this code is extracted from there into this extension

**Comment by geoand** [comment]
I'll put it on my list :)

**Pull request merged**
